@startuml
start
:Инициализировать устройство Orange Pi Zero 2W;
:Загрузить Kali Linux;
:Проверить наличие необходимых утилит (aircrack-ng, tcpdump);

if (Утилиты установлены?) then (нет)
  :Установить недостающие пакеты;
  :Обновить базы данных;
else (да)
endif

:Вывести меню выбора режима работы;

while (Выполнять аудит?) is (да)
  :Отобразить доступные режимы:
  === 1. Сканирование сетей ===
  === 2. Атака deauth ===
  === 3. Формирование отчета ===
  === 4. Выход ===;
  
  if (Выбран режим 1?) then (да)
    :Запустить сканирование Wi-Fi сетей;
    :Захватить пакеты (capture);
    :Парсить полученные данные;
    :Вывести список сетей (SSID, BSSID, канал);
    :Сохранить результаты в лог;
  elseif (Выбран режим 2?) then (да)
    :Выбрать целевую сеть из списка;
    :Указать MAC-адрес клиента (опционально);
    :Запустить атаку deauth;
    :Отправить пакеты деавторизации;
    :Зафиксировать результат атаки;
    :Сохранить в лог;
  elseif (Выбран режим 3?) then (да)
    :Собрать данные из журнала;
    :Сформировать отчет в формате PDF;
    :Сохранить отчет на устройство;
    :Вывести путь к файлу отчета;
  elseif (Выбран режим 4?) then (да)
    :Завершить сеанс аудита;
    break
  else (некорректный ввод)
    :Вывести сообщение об ошибке;
    :Запросить повторный ввод;
  endif
repeat while (Продолжить работу?) is (да)
-> нет;
:Выключить устройство;
stop
@enduml
